# Generated by Django 5.1.1 on 2025-10-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtask',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='jobtask',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['order'], name='jobops_jobt_order_7493d7_idx'),
        ),
    ]
