# Generated by Django 5.1.1 on 2025-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobops', '0002_alter_jobtask_options_jobtask_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtask',
            name='step',
            field=models.CharField(choices=[('inspection', 'Inspection'), ('installation', 'Installation'), ('testing', 'Testing'), ('configuration', 'Configuration'), ('training', 'Training'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
